# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BabyShop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BabyShop
	pod 'SnapKit','~> 5.0.1'
	pod 'Alamofire','~> 5.0.2'
  	pod 'SwiftyJSON','~> 5.0.0'
  	pod 'Kingfisher','~> 5.7.1'
	pod 'Moya','~> 14.0.0'
	pod 'Moya/RxSwift'
	pod 'RxSwift','~> 5.0.1'
  	pod 'RxSwiftExt','~> 5.2.0'
  	pod 'RxGesture','~> 3.0.1'
	pod 'RxDataSources','~> 4.0.1'
	pod 'RealmSwift', '~> 4.3.1'
	pod 'RxRealm', '~> 2.0.0'
	pod 'SwiftLint','~> 0.38.2'
	pod 'AloeStackView','~> 1.2.0'
	pod 'SnapKit','~> 5.0.1'

  target 'BabyShopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BabyShopUITests' do
    # Pods for testing
  end

end
